volumes:
  boss-app-data:
    external: true

services:

  backend:
    build: ./backend
    restart: on-failure
    env_file: ./. env_file
    ports:


  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - boss-app-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: boss-app
      POSTGRES_PASSWORD: boss-app
      POSTGRES_DB: boss-app
    ports:
      - 15432:5432

  frontend:
    image: node:lts-bullseye
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_BOSS_API_HOST: http://localhost:8000
