volumes:
  boss-app-data:
    external: true
# x-environment:
#   &PLAID_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
#   PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
#   PLAID_SECRET: ${PLAID_SECRET}
#   PLAID_PRODUCTS: ${PLAID_PRODUCTS}
#   PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
#   PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
#   PLAID_ENV: ${PLAID_ENV}
services:
  postgres:
    image: "postgres:14.2-bullseye"
    container_name: postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile
    volumes:
      - boss-app-data:/var/lib/postgresql/data
    ports:
      - 15432:5432

  backend:
    depends_on:
      - postgres
    image: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=boss_user
      - SPRING_DATASOURCE_PASSWORD=boss-pw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    # networks:
    #   - "plaid"
  java:
    networks:
      - "plaid"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./java/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PLAID_CLIENT_ID=$PLAID_CLIENT_ID
      - PLAID_SECRET=$PLAID_SECRET
      - PLAID_PRODUCTS=$PLAID_PRODUCTS
      - PLAID_COUNTRY_CODES=$PLAID_COUNTRY_CODES
      - PLAID_REDIRECT_URI=$PLAID_REDIRECT_URI
      - PLAID_ENV=$PLAID_ENV

  frontend:
    # depends_on:
    #   - backend
    # volumes:
    #   - ./frontend:/app
    networks:
      - "plaid"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      # HOST_OS: ${OS}
      # NODE_ENV: development
      # HOST: "0.0.0.0"
      # PUBLIC_URL: http://localhost:3000
      - REACT_APP_API_HOST
      # REACT_APP_BOSS_API_HOST: http://localhost:8081


networks:
  plaid:
    name: plaid
